#!/bin/csh -f                                                                                                                                                                                                                           

  latex --src-specials $1.tex
  bibtex $1
  latex --src-specials $1.tex
  latex --src-specials $1.tex
  dvips -o $1.ps $1.dvi
  ps2pdf $1.ps

